### ISSUE TITLE
Hey guys

### ISSUE THREAD

**Issue by dkern27** [avmeer/GameMakerProject#1]
Hey guys, it's me. Just wanted to let you know I think this is a great project. lol jk

**Comment by dkern27** [comment]
Why hasn't this been resolved yet? wtf are you even paying attention to me?

**Comment by avmeer** [comment]
....................../´¯/) 
....................,/¯../ 
.................../..../ 
............./´¯/'...'/´¯¯`·¸ 
........../'/.../..../......./¨¯\ 
........('(...´...´.... ¯~/'...') 
.........\.................'...../ 
..........''...\.......... _.·´ 
............\..............( 
..............\.............\...
